### ISSUE TITLE
Fix failing phpunit tests

### ISSUE THREAD

**Issue by nerrad** [eventespresso/ee4-infusionsoft#1]
see https://travis-ci.org/eventespresso/ee4-infusionsoft/jobs/370924105

**Comment by mnelson4** [comment]
I explored this a bit and found some request data is spilling over from one unit test to another.
Specifically, during `hook_when_setting_cookie`, data set during `test_set_affiliate_cookie__by_code` by using `EE_Registry::instance()->REQ->set('ref', 'monkey');` is still around.
Are those tests setting request data in a deprecated way @tn3rb? Or are requests not being reset between tests?

**Comment by mnelson4** [comment]
Created an issue https://github.com/eventespresso/event-espresso-core/issues/353 for a better solution that would entirely reset the request between unit tests, but for now it would be helpful to just fix the test

**Comment by mnelson4** [comment]
pull request accepted so this should be good
