### ISSUE TITLE
Create Privacy Policy Content

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/ee4-infusionsoft#5]
We need to define Infusionsoft's privacy policy, related to https://github.com/eventespresso/ee4-infusionsoft/issues/3

**Comment by mnelson4** [comment]
Seth should I work on this? It should be an hour or two to create the HTML content and hook into the EE core system

**Comment by sethshoultes** [comment]
Yes, please. There's also another Infusionsoft GDPR issue in the Next pipeline.

**Comment by mnelson4** [comment]
I'm actually using https://github.com/eventespresso/ee4-infusionsoft/pull/4 for the code. While the privacy policy page content and the code to hook it in are different, they're joined at the hip so I figured may as well put them in the same pull request

**Comment by mnelson4** [comment]
meuh, let's simplify it and just do everything on #4 's PR
