### ISSUE TITLE
Set higher limit for tags and add a filter

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/ee4-infusionsoft#8]
Codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/11489

Per @joshfeck 

More than a few users have complained that not all of their tags are included in the new metabox added in #11144 - EE4 Infusionsoft tag all event attendees. In that ticket there was a comment that said "It shows the first 100 IS tags, and the event admin can select as many as they like." One hundred is apparently not enough.

Can the limit be raised to 200 and can a filter hook be added to allow changing the limit?

Reported again here:
https://eventespresso.com/topic/infusionsoft-tags-not-available-at-ee/

**Comment by mnelson4** [comment]
I just checked, the maximum limit is 1000 eh. See https://developer.infusionsoft.com/docs/xml-rpc/#data-find-a-record-by-matching-a-specific-field

**Comment by mnelson4** [comment]
created https://github.com/eventespresso/ee4-infusionsoft/pull/9 to address this

**Comment by joshfeck** [comment]
PR #9 was merged.
